version: "3"

services:
  app:
    volumes:
      - ./:/var/www/app
    build: ./
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
    networks:
      - book-gallery-network
    command: ["npm", "run", "dev"]

networks:
  book-gallery-network:
    external:
      name: book-gallery-network
